/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Recursos.Conexion;
import Recursos.controlador;
import java.sql.CallableStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.WindowConstants;

/**
 *
 * @author ECANALES
 */
public class ModificarProyecto extends javax.swing.JFrame {

    controlador control = new controlador();
    int cantproy, id_proy;

    public ModificarProyecto(int cantproyectos, int id_proyecto) {
        this.cantproy=cantproyectos;
        this.id_proy = id_proyecto;
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        SpinnerNumberModel spinnerModel = new SpinnerNumberModel(1, 1, cantproyectos, 1);
        prioriSpin.setModel(spinnerModel);
        
    }

    private ModificarProyecto() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        codproy_text = new javax.swing.JTextField();
        nombre_text = new javax.swing.JTextField();
        sponsor_text = new javax.swing.JTextField();
        gestor_text = new javax.swing.JTextField();
        fechainicio_text = new javax.swing.JTextField();
        fechafin_text = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        prioriSpin = new javax.swing.JSpinner();
        EstadoCbox = new javax.swing.JComboBox<>();
        FaseCbox = new javax.swing.JComboBox<>();
        jActProyBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Código proyecto");

        jLabel2.setText("Nombre");

        jLabel3.setText("Sponsor");

        jLabel4.setText("Gestor");

        jLabel5.setText("Fecha de Inicio");

        jLabel6.setText("Fecha de Fin");

        jLabel7.setText("Prioridad");

        jLabel8.setText("Estado");

        jLabel9.setText("Fase");

        EstadoCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EN PROCESO", "FINALIZADO", "SUSPENDIDO", "CANCELADO" }));

        FaseCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INICIO", "PLANIFICACION", "EJECUCION", "SEGUIMIENTO", "CIERRE" }));

        jActProyBtn.setText("Actualizar proyecto");
        jActProyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jActProyBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre_text, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(gestor_text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(sponsor_text, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(codproy_text, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(fechafin_text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(fechainicio_text, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FaseCbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EstadoCbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prioriSpin)))
                    .addComponent(jActProyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codproy_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(prioriSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombre_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(EstadoCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sponsor_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(FaseCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(gestor_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jActProyBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fechainicio_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fechafin_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jActProyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jActProyBtnActionPerformed
        CallableStatement sql;
        try {
            String fechain = fechainicio_text.getText();
            String fechafin = fechafin_text.getText();
            sql = Conexion.getConexion().prepareCall("{CALL sp_modificar_proy(?,?,?,?,?,?,?,?,?,?,?)}");
            sql.setInt(1, id_proy);
            sql.setString(2, codproy_text.getText());
            sql.setString(3, nombre_text.getText());
            sql.setString(4, sponsor_text.getText());
            sql.setString(5, gestor_text.getText());
            sql.setString(6, FaseCbox.getSelectedItem().toString());
            sql.setString(7, fechainicio_text.getText());
            sql.setString(8, fechafin_text.getText());
            sql.setInt(9, control.avanceporc(fechain, fechafin));
            sql.setString(10, EstadoCbox.getSelectedItem().toString());
            sql.setInt(11, (int) prioriSpin.getValue());
            sql.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(CrearProyecto.class.getName()).log(Level.SEVERE, null, ex);
        }
        control.exportTableToCSV("cartera_proyectos", "Select * from cartera_proyectos", "D:/BD OTI GESTION/cartera_proyectos.csv");
        JOptionPane.showMessageDialog(null, "Registros Actualizados.");
    }//GEN-LAST:event_jActProyBtnActionPerformed
    public void LlenarDatosModif(int id) {
        String consulta = "select codigo_proyecto, nombre, sponsor, gestor, fecha_ini, fecha_fin, prioridad, estado, fase from cartera_proyectos where cartera_proyectos.id_proy = '" + id + "'";
        String fase;
        String estado;
        int prioridad;
        codproy_text.setText(control.DevolverRegistroBD(consulta, 1));
        nombre_text.setText(control.DevolverRegistroBD(consulta, 2));
        sponsor_text.setText(control.DevolverRegistroBD(consulta, 3));
        gestor_text.setText(control.DevolverRegistroBD(consulta, 4));
        fechainicio_text.setText(control.DevolverRegistroBD(consulta, 5));
        fechafin_text.setText(control.DevolverRegistroBD(consulta, 6));
        prioriSpin.setValue(prioridad=Integer.parseInt(control.DevolverRegistroBD(consulta, 7)));
        //FaseCbox.setSelectedItem(control.DevolverRegistroBD(consulta, 8));
        
        estado = control.DevolverRegistroBD(consulta, 8);
        fase = control.DevolverRegistroBD(consulta, 9);
        //EstadoCbox.setSelectedItem(control.DevolverRegistroBD(consulta, 9));
        
        if (null == fase) {
            FaseCbox.setSelectedIndex(4);
        } else switch (fase) {
            case "INICIO" -> FaseCbox.setSelectedIndex(0);
            case "PLANIFICACION" -> FaseCbox.setSelectedIndex(1);
            case "EJECUCION" -> FaseCbox.setSelectedIndex(2);
            case "SEGUIMIENTO" -> FaseCbox.setSelectedIndex(3);
            default -> FaseCbox.setSelectedIndex(4);
        }
        
        if (null == estado) {
            EstadoCbox.setSelectedIndex(3);
        } else switch (estado) {
            case "EN PROCESO" -> EstadoCbox.setSelectedIndex(0);
            case "FINALIZADO" -> EstadoCbox.setSelectedIndex(1);
            case "SUSPENDIDO" -> EstadoCbox.setSelectedIndex(2);
            case "CANCELADO" -> EstadoCbox.setSelectedIndex(3);
            default -> EstadoCbox.setSelectedIndex(3);
        }
        
       
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarProyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarProyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EstadoCbox;
    private javax.swing.JComboBox<String> FaseCbox;
    private javax.swing.JTextField codproy_text;
    private javax.swing.JTextField fechafin_text;
    private javax.swing.JTextField fechainicio_text;
    private javax.swing.JTextField gestor_text;
    private javax.swing.JButton jActProyBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombre_text;
    private javax.swing.JSpinner prioriSpin;
    private javax.swing.JTextField sponsor_text;
    // End of variables declaration//GEN-END:variables
}
